### ISSUE TITLE
Species list not loading on Android app

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OpenTreeMap-Android#208]
This is for both TreeMapLA and the generic OTM app. I get a "could not load species list" message when trying to access the list both for filtering and adding/editing a tree.

**Comment by dboyer** [comment]
This is on production and likely related to the recent deployment.

**Comment by jwalgran** [comment]
Not android specific

https://github.com/OpenTreeMap/OTM2/issues/1964
